version: "3.9"

services:
  db:
    image: postgres:16
    container_name: api-db
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:latest
    container_name: myapi-migrate
    depends_on:
      - db
    command: -path=/migrations -database ${DATABASE_URL} up
    volumes:
      - ./migrations:/migrations

  api:
    build: .
    container_name: myapi
    depends_on:
      - db
      - migrate
    environment:
      PORT: ${PORT}
      DATABASE_URL: postgres://myapi:secret@db:5432/myapi?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"

volumes:
  db_data: