config:
  server:
    read_timeout: 5 # seconds
    write_timeout: 10 # seconds
    shutdown_timeout: 15 # seconds
  token:
    token_duration: 60 # minutes
  db:
    max_conns: 10
    max_idle_conns: 2
    max_conn_lifetime: 30 # minutes
    max_conn_idle_time: 5 # minutes
  logging:
    max_size: 10 # MB
    max_backups: 3
    max_age: 30  # days
    compress: true
  pagination:
    default_page_size: 20
    max_page_size: 200